version: '3'
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    command: -p 5432
    container_name: anylist
